scss_files: 'templating/**/*.scss'

linters:

  PropertySortOrder:
    enabled: false
    ignore_unspecified: true
    min_properties: 2
    separate_groups: false

  TrailingWhitespace:
    enabled: false